# Generated by Django 3.1.3 on 2020-11-27 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popularity', models.CharField(max_length=120)),
                ('director', models.CharField(max_length=120)),
                ('genre', models.TextField()),
                ('imdb_score', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name_plural': 'Name',
            },
        ),
        migrations.CreateModel(
            name='MoviePoster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_url', models.TextField()),
                ('name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='movies.movies', verbose_name='Name')),
            ],
        ),
    ]
